apiVersion: v1
kind: Pod
metadata:
  name: nvidia-cuda-pod
spec:
  containers:
    - name: cuda-container
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      resources:
        limits:
          nvidia.com/gpu: "{{ .Values.resource.nGPU }}"
      command: ["stress"]
      args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
